version: 2
jobs:
  build:
    working_directory: "~/project/Example"
    # Specify the Xcode version to use
    macos:
      xcode: "11.2.0"

    steps:
      - checkout:
          path: ~/project
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      # Install CocoaPods
      # - run:
      #     name: Install CocoaPods
      #     command: pod install

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: bundle exec fastlane tests

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      # - store_test_results:
      #     path: test_output/report.xml
      # - store_artifacts:
      #     path: /tmp/test-results
      #     destination: scan-test-results
      # - store_artifacts:
      #     path: ~/Library/Logs/scan
      #     destination: scan-logs